language: r
cache: packages
r_packages:
- covr
- drat
- pkgdown
before_install:
- bash make.sh
after_success:
- Rscript -e 'library(covr); codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  deploy.sh
- Rscript -e 'install.packages("sykdomspuls",repos="https://folkehelseinstituttet.github.io/drat/");pkgdown::build_site()'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  local-dir: docs
  on:
    branch: master
env:
  global:
    secure: zvumGFapNpbcv+BE1nr+wvWAT4DGZcssDEuOF8huwGeFr+MoV//wS53RdMrGqYBVECF+PSWUOSNZicRwarHbgWsj0S3eYFDpn78e5y0vBl04U+bgmokEcenXL5poTuPE02FTPShL4N5cLBQ8BOmmvL6UzmJK7e7tVd+Fn+0hEk2RQpsUDHxyc9LP0fHMuPyRWevPqoqiJjbIPUYBfR43R5gIrcAYlDdtmUl2nIZ26dNBeH+heOfuaMh+CqkJLZ3SBU6qdWsCVG9Ws4WDrv3f2JH76xaZiZTqLytAvByTCSbmhGWvd0QtEmOTytzjdfBLyYOrGpw0cOxPBPrxFfUv/IA1idN4UIIAkm+DredoQ4TgsuWBykK+/K8y/k7cBaWRhYvqgSZeqtw2YpXAyANWgLtaAdxlsGFJ38Fh935R+QI6RzrgVXJuxuH0DOxuKiwvnPP1Jgltw1zva76THI8LaYez20tUpOXv4/dkgsW+lvqRs1sHiDVUZ7t2kQ8T7sm0H42jB00dqfuiXtczdiP+s9/En1B/3UWK4tz+4S5LM9HjxCQ+GoK0tVX61EzICMAhZrPTwpKdqzeJPNGteQJ/TzfvsKjgq3wziJPAtUPyL7ksJQEcVCJIGFfmearGBMAPxSRU4eOV/V6gGoytdl5HMY2OxLGYmCzBMhj2teAn/zI=
